# Generated by Django 3.1.7 on 2021-03-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carte', models.IntegerField()),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cheque', models.IntegerField()),
                ('nom_banque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.IntegerField()),
                ('ref_article', models.IntegerField()),
                ('individu', models.ManyToManyField(to='referentiel.Individu')),
            ],
        ),
    ]
